# Generated by Django 3.0.2 on 2020-01-14 11:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
            ],
        ),
        migrations.CreateModel(
            name='MarkOfQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('administrative_region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.AdministrativeRegion')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('geographic_region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.GeographicRegion')),
            ],
        ),
        migrations.AddField(
            model_name='administrativeregion',
            name='geographic_region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.GeographicRegion'),
        ),
    ]
