# Generated by Django 3.0.2 on 2020-01-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('location', '0001_initial'), ('location', '0002_auto_20200115_0658'), ('location', '0003_auto_20200115_0906'), ('location', '0004_auto_20200116_0842'), ('location', '0005_auto_20200117_0954'), ('location', '0006_auto_20200117_1201')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'administrative region',
                'verbose_name_plural': 'administrative regions',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_regions', to='location.Country')),
            ],
            options={
                'verbose_name': 'geographic region',
                'verbose_name_plural': 'geographic regions',
            },
        ),
        migrations.CreateModel(
            name='MarkOfQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('administrative_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.AdministrativeRegion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('geographic_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.GeographicRegion')),
            ],
            options={
                'verbose_name': 'mark of quality',
                'verbose_name_plural': 'mark of qualities',
            },
        ),
        migrations.AddField(
            model_name='administrativeregion',
            name='geographic_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_regions', to='location.GeographicRegion'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('administrative_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.AdministrativeRegion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('geographic_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.GeographicRegion')),
                ('mark_of_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.MarkOfQuality')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
        ),
        migrations.AlterField(
            model_name='markofquality',
            name='administrative_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_of_qualities', to='location.AdministrativeRegion'),
        ),
        migrations.AlterField(
            model_name='administrativeregion',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
