# Generated by Django 3.0.2 on 2020-01-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeregion',
            options={'verbose_name': 'administrative region', 'verbose_name_plural': 'administrative regions'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'verbose_name': 'geographic region', 'verbose_name_plural': 'geographic regions'},
        ),
        migrations.AlterModelOptions(
            name='markofquality',
            options={'verbose_name': 'mark of quality', 'verbose_name_plural': 'mark of qualities'},
        ),
    ]
