# Generated by Django 3.0.2 on 2020-01-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerModel',
            new_name='Package',
        ),
    ]
