# Generated by Django 3.0.2 on 2020-01-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200115_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeregion',
            name='geographic_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_regions', to='location.GeographicRegion'),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_regions', to='location.Country'),
        ),
        migrations.AlterField(
            model_name='markofquality',
            name='administrative_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_of_qualities', to='location.AdministrativeRegion'),
        ),
    ]
